In [51]:
import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string

In [52]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\jomin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\jomin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\jomin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\jomin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\jomin\AppData\Roaming\nltk_data...
[nltk_data]    | 

True

In [53]:
data = pd.read_csv("./twcs/twcs.csv", nrows=5000)
df_text = data[["text"]]
df_text["text"] = df_text["text"].astype(str)
df_text['text'].tail()


C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\107890382.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text["text"] = df_text["text"].astype(str)


4995    @117290 Hm, they should definitely resume if a...
4996    @117290 That's where they need to be on, so ch...
4997    @115940 Can you guys maybe like....FIX your st...
4998    @117291 Hulu is only available in the U.S. rig...
4999    @115940 when will the platform available in la...
Name: text, dtype: object

In [54]:
#lowercase
df_text["text"]=df_text["text"].str.lower()
df_text.head()

C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\4083228405.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text["text"]=df_text["text"].str.lower()


text
0  @115712 i understand. i would like to assist y...
1      @sprintcare and how do you propose we do that
2  @sprintcare i have sent several private messag...
3  @115712 please send us a private message so th...
4                                 @sprintcare i did.

In [57]:
#punctuation
punctuation_words=string.punctuation
def remove_punc(text):
    return text.translate(str.maketrans("","",punctuation_words))
df_text['text']=df_text['text'].apply(remove_punc)
df_text['text'].head()

C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\3238206993.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_punc)


0    115712 i understand i would like to assist you...
1         sprintcare and how do you propose we do that
2    sprintcare i have sent several private message...
3    115712 please send us a private message so tha...
4                                     sprintcare i did
Name: text, dtype: object

In [58]:
#stop words
from nltk.corpus import stopwords
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jomin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [60]:
def remove_stopwords(text):
    new_text = []
    for words in text.split():
        if words in stopwords.words('english'):
            new_text.append("")
        else:
            new_text.append(words)
    buffer=" ".join(new_text)
    return " ".join(buffer.split())

df_text['text']=df_text['text'].apply(remove_stopwords)
df_text['text'].head()



C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\3572930168.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_stopwords)


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private messages one r...
3    115712 please send us private message assist c...
4                                           sprintcare
Name: text, dtype: object

In [61]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
df_text['text']=df_text['text'].apply(remove_stopwords)
df_text['text'].head()


C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\3142345659.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_stopwords)


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private messages one r...
3    115712 please send us private message assist c...
4                                           sprintcare
Name: text, dtype: object

In [63]:
def remove_html(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'', text)

df_text['text']=df_text['text'].apply(remove_html)
# def remove_char(text):
#     return re.sub(r'@','', text)

# print(remove_char('@jomin is good'))
# df_text['text']=df_text['text'].apply(remove_char)
df_text['text'].head()

C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\4187326694.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_html)


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private messages one r...
3    115712 please send us private message assist c...
4                                           sprintcare
Name: text, dtype: object

In [66]:
chat_words_str = """
AFAIK=As Far As I Know
AFK=Away From Keyboard
ASAP=As Soon As Possible
ATK=At The Keyboard
ATM=At The Moment
A3=Anytime, Anywhere, Anyplace
BAK=Back At Keyboard
BBL=Be Back Later
BBS=Be Back Soon
BFN=Bye For Now
B4N=Bye For Now
BRB=Be Right Back
BRT=Be Right There
BTW=By The Way
B4=Before
B4N=Bye For Now
CU=See You
CUL8R=See You Later
CYA=See You
FAQ=Frequently Asked Questions
FC=Fingers Crossed
FWIW=For What It's Worth
FYI=For Your Information
GAL=Get A Life
GG=Good Game
GN=Good Night
GMTA=Great Minds Think Alike
GR8=Great!
G9=Genius
IC=I See
ICQ=I Seek you (also a chat program)
ILU=ILU: I Love You
IMHO=In My Honest/Humble Opinion
IMO=In My Opinion
IOW=In Other Words
IRL=In Real Life
KISS=Keep It Simple, Stupid
LDR=Long Distance Relationship
LMAO=Laugh My A.. Off
LOL=Laughing Out Loud
LTNS=Long Time No See
L8R=Later
MTE=My Thoughts Exactly
M8=Mate
NRN=No Reply Necessary
OIC=Oh I See
PITA=Pain In The A..
PRT=Party
PRW=Parents Are Watching
ROFL=Rolling On The Floor Laughing
ROFLOL=Rolling On The Floor Laughing Out Loud
ROTFLMAO=Rolling On The Floor Laughing My A.. Off
SK8=Skate
STATS=Your sex and age
ASL=Age, Sex, Location
THX=Thank You
TTFN=Ta-Ta For Now!
TTYL=Talk To You Later
U=You
U2=You Too
U4E=Yours For Ever
WB=Welcome Back
WTF=What The F...
WTG=Way To Go!
WUF=Where Are You From?
W8=Wait...
7K=Sick:-D Laugher
"""

In [68]:
chatwords_dict = {}
chatwords_list = []
for line in chat_words_str.split('\n'):
    if line!='':
       chat_key=line.split('=')[0]
       chat_expanded=line.split('=')[1]
       chatwords_list.append(chat_key)
       chatwords_dict[chat_key] = chat_expanded
chatwords_list=set(chatwords_list)
print(chatwords_dict)
def remove_chatwords(text):
    new_text = []
    for w in text.split():
        if w.upper() in chatwords_list:
            new_text.append(chatwords_dict[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

text="WTG"
print(remove_chatwords(text))
df_text['text']=df_text['text'].apply(remove_chatwords)
df_text['text'].head()


{'AFAIK': 'As Far As I Know', 'AFK': 'Away From Keyboard', 'ASAP': 'As Soon As Possible', 'ATK': 'At The Keyboard', 'ATM': 'At The Moment', 'A3': 'Anytime, Anywhere, Anyplace', 'BAK': 'Back At Keyboard', 'BBL': 'Be Back Later', 'BBS': 'Be Back Soon', 'BFN': 'Bye For Now', 'B4N': 'Bye For Now', 'BRB': 'Be Right Back', 'BRT': 'Be Right There', 'BTW': 'By The Way', 'B4': 'Before', 'CU': 'See You', 'CUL8R': 'See You Later', 'CYA': 'See You', 'FAQ': 'Frequently Asked Questions', 'FC': 'Fingers Crossed', 'FWIW': "For What It's Worth", 'FYI': 'For Your Information', 'GAL': 'Get A Life', 'GG': 'Good Game', 'GN': 'Good Night', 'GMTA': 'Great Minds Think Alike', 'GR8': 'Great!', 'G9': 'Genius', 'IC': 'I See', 'ICQ': 'I Seek you (also a chat program)', 'ILU': 'ILU: I Love You', 'IMHO': 'In My Honest/Humble Opinion', 'IMO': 'In My Opinion', 'IOW': 'In Other Words', 'IRL': 'In Real Life', 'KISS': 'Keep It Simple, Stupid', 'LDR': 'Long Distance Relationship', 'LMAO': 'Laugh My A.. Off', 'LOL': 'Laug

C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\3419884024.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_chatwords)


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private messages one r...
3    115712 please send us private message assist c...
4                                           sprintcare
Name: text, dtype: object

In [69]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

df_text['text']=df_text['text'].apply(remove_urls)
df_text['text'].head()


C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\1493852899.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_urls)


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private messages one r...
3    115712 please send us private message assist c...
4                                           sprintcare
Name: text, dtype: object

In [74]:
# import textblob
# from textblob import TextBlob
# def correct_spelling(text):
#     txtblob = TextBlob(text)
#     return txtblob.correct().string
# df_text['text'].apply(correct_spelling)
# !pip install pyspellchecker
from spellchecker import SpellChecker

spell = SpellChecker()
def correct_spellings(text):
    corrected_text = []
    misspelled_words = spell.unknown(text.split())
    for word in text.split():
        if word in misspelled_words:
            corrected_text.append(spell.correction(word))
        else:
            corrected_text.append(word)
    return " ".join(corrected_text)
        
text = df_text['text'][0]
print(correct_spellings(text))
# df_text['text']=df_text['text'].apply(correct_spellings)
df_text['text'].head()


115712 understand would like assist would need get private secured link assist


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private messages one r...
3    115712 please send us private message assist c...
4                                           sprintcare
Name: text, dtype: object

In [99]:
import emoji

In [100]:
def remove_emoji(text):
    clean_text=emoji.demojize(text)
    return clean_text
remove_emoji(text)
df_text['text']=df_text['text'].apply(remove_emoji)

import re
def remove_emojis_manually(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F700-\U0001F77F"  # alchemical symbols
                               u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                               u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                               u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                               u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                               u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                               u"\U00002702-\U000027B0"  # Dingbats
                               u"\U000024C2-\U0001F251"
                               "]+", flags=re.UNICODE)
    clean_text = emoji_pattern.sub(r'', text)
    return clean_text

df_text['text']=df_text['text'].apply(remove_emojis_manually)


C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\4030439885.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_emoji)
C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\4030439885.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['text']=df_text['text'].apply(remove_emojis_manually)


In [101]:
nlp = spacy.load("en_core_web_sm")
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df_text['stem']=df_text['text'].apply(stem_words)

C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\2316338959.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['stem']=df_text['text'].apply(stem_words)


In [102]:
df_text['stem']

0       115712 understand would like assist would need...
1                                        sprintcar propos
2       sprintcar sent sever privat messag one respond...
3       115712 pleas send us privat messag assist clic...
4                                               sprintcar
                              ...                        
4995    117290 hm definit resum alreadi enabl disappea...
4996    117290 that need check home screengtsettingsgt...
4997    115940 guy mayb likefix stuff longest time cap...
4998    117291 hulu avail us right well sure share int...
4999    115940 platform avail latinamerica specif arge...
Name: stem, Length: 5000, dtype: object

In [103]:
from nltk.stem import WordNetLemmatizer

def lammatization(text):
    words=text.split()

    lemmetizer=WordNetLemmatizer()

    lemetized_word=" ".join([lemmetizer.lemmatize(word) for word in words])
    return " ".join(lemetized_word.split())

In [104]:
df_text['lammatization'] = df_text['text'].apply(lammatization)
df_text['lammatization'].head()

C:\Users\jomin\AppData\Local\Temp\ipykernel_25456\1472223814.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['lammatization'] = df_text['text'].apply(lammatization)


0    115712 understand would like assist would need...
1                                   sprintcare propose
2    sprintcare sent several private message one re...
3    115712 please send u private message assist cl...
4                                           sprintcare
Name: lammatization, dtype: object

In [114]:
#encoding 
#one hot encoding
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

unique_words = set()
for sentence in df_text['lammatization']:
    for word in sentence.split():
        unique_words.add(word.lower())
# print(unique_words)
word_to_index = {}
for sentence in df_text['lammatization']:
    for i, word in enumerate(sentence.split()):
        word_to_index[word] = i
# print(word_to_index)

one_hot_vectors = []
for sentence in df_text['lammatization']:
    sentence_vectors = []
    for word in sentence.split():
        vector = np.zeros(len(unique_words))
        vector[word_to_index[word]] = 1
        sentence_vectors.append(vector)
    one_hot_vectors.append(sentence_vectors)
for vector in one_hot_vectors[0]:
    print(vector)



[1. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 1. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [81]:
df_text['lammatization'][0]

'115712 understand would like assist would need get private secured link assist'

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
BOW=CountVectorizer()
document_matrix=BOW.fit_transform(df_text['lammatization'])


In [83]:
BOW.vocabulary_

{'115712': 75,
 'understand': 9198,
 'would': 9611,
 'like': 6410,
 'assist': 2462,
 'need': 6911,
 'get': 4526,
 'private': 7531,
 'secured': 8197,
 'link': 6425,
 'sprintcare': 8535,
 'propose': 7575,
 'sent': 8230,
 'several': 8263,
 'message': 6694,
 'one': 7099,
 'responding': 7930,
 'usual': 9300,
 'please': 7396,
 'send': 8223,
 'click': 3145,
 'top': 9005,
 'profile': 7553,
 'gain': 4474,
 'detail': 3678,
 'account': 2078,
 'worst': 9609,
 'customer': 3496,
 'service': 8247,
 '115713': 76,
 'saddening': 8086,
 'hear': 4739,
 'shoot': 8303,
 'dm': 3801,
 'look': 6487,
 'kc': 6198,
 'gonna': 4576,
 'magically': 6565,
 'change': 3043,
 'connectivity': 3305,
 'whole': 9534,
 'family': 4228,
 'concern': 3268,
 'wed': 9480,
 'direct': 3732,
 'aa': 2029,
 'since': 8354,
 'signed': 8335,
 'yousince': 9702,
 'day': 3555,
 'definitely': 3606,
 'work': 9596,
 'long': 6481,
 'experiencing': 4174,
 'issue': 6045,
 '115714': 77,
 'all': 2228,
 'lie': 6398,
 'great': 4609,
 'connection': 3304

In [84]:
document_matrix[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [85]:
bigram=CountVectorizer(ngram_range=(1,1))
bigramvocab=bigram.fit_transform(df_text['lammatization'])


In [86]:
bigram.vocabulary_


{'115712': 75,
 'understand': 9198,
 'would': 9611,
 'like': 6410,
 'assist': 2462,
 'need': 6911,
 'get': 4526,
 'private': 7531,
 'secured': 8197,
 'link': 6425,
 'sprintcare': 8535,
 'propose': 7575,
 'sent': 8230,
 'several': 8263,
 'message': 6694,
 'one': 7099,
 'responding': 7930,
 'usual': 9300,
 'please': 7396,
 'send': 8223,
 'click': 3145,
 'top': 9005,
 'profile': 7553,
 'gain': 4474,
 'detail': 3678,
 'account': 2078,
 'worst': 9609,
 'customer': 3496,
 'service': 8247,
 '115713': 76,
 'saddening': 8086,
 'hear': 4739,
 'shoot': 8303,
 'dm': 3801,
 'look': 6487,
 'kc': 6198,
 'gonna': 4576,
 'magically': 6565,
 'change': 3043,
 'connectivity': 3305,
 'whole': 9534,
 'family': 4228,
 'concern': 3268,
 'wed': 9480,
 'direct': 3732,
 'aa': 2029,
 'since': 8354,
 'signed': 8335,
 'yousince': 9702,
 'day': 3555,
 'definitely': 3606,
 'work': 9596,
 'long': 6481,
 'experiencing': 4174,
 'issue': 6045,
 '115714': 77,
 'all': 2228,
 'lie': 6398,
 'great': 4609,
 'connection': 3304

In [87]:
bigram=CountVectorizer(ngram_range=(1,2))
bigramvocab=bigram.fit_transform(df_text['lammatization'])
bigram=CountVectorizer(ngram_range=(2,2))
bigramvocab=bigram.fit_transform(df_text['lammatization'])
bigram=CountVectorizer(ngram_range=(3,3))
bigramvocab=bigram.fit_transform(df_text['lammatization'])

In [88]:
bigram.vocabulary_


{'115712 understand would': 147,
 'understand would like': 35171,
 'would like assist': 37481,
 'like assist would': 21304,
 'assist would need': 6672,
 'would need get': 37524,
 'need get private': 23899,
 'get private secured': 15858,
 'private secured link': 27083,
 'secured link assist': 29485,
 'sprintcare sent several': 31518,
 'sent several private': 29908,
 'several private message': 30196,
 'private message one': 27080,
 'message one responding': 23059,
 'one responding usual': 24896,
 '115712 please send': 145,
 'please send private': 26561,
 'send private message': 29835,
 'private message assist': 27078,
 'message assist click': 23027,
 'assist click message': 6637,
 'click message top': 9627,
 'message top profile': 23080,
 'private message gain': 27079,
 'message gain detail': 23048,
 'gain detail account': 15538,
 'sprintcare worst customer': 31523,
 'worst customer service': 37408,
 '115713 saddening hear': 148,
 'saddening hear please': 29030,
 'hear please shoot': 173

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df_text['lammatization']).toarray()
tfidf.get_feature_names_out()
tfidf.idf_

array([8.82424599, 8.82424599, 8.41878088, ..., 8.82424599, 8.82424599,
       8.82424599])

In [90]:
df_text['lammatization'][1]

'sprintcare propose'

In [91]:
OneHotEncoder
# Advantage
# It's relatively straightforward to implement and enables us to apply machine-learning algorithms to data with categorical columns
# One-hot encoding has the advantage that the result is binary rather than ordinal and that everything sits in an orthogonal vector space
# Disadvantage
# The problem is that it increases dimensionality so training becomes slower and more complex
# When we one-hot encode categorical data, we unknowingly introduce perfect multicollinearity
# Increase in dimensionality, after adding several columns based on categorical variables which may result in an increase in the computational cost

sklearn.preprocessing._encoders.OneHotEncoder

In [94]:
# Bag of words
# Advantage
# One advantage is that it provides a feature representation of free-form text that can be used by machine learning algorithms for processing language
# Captures the essence of the document by representing it as a set of its constituent words.	
# Robust to noise, as representation of the document is based only on the occurrence of its constituent words.	
# Disadvantage
# It does not take into account the semantics of the language, as it is based on a system of binary logic
# The bag-of-words approach may not capture the syntactic and layout information present in the text
# Unsuitable for tasks, where the order of words is important.


In [95]:
# N-Gram
# Disadvantage
# some n-grams may not occur frequently or at all in the training data, resulting in low or zero probabilities

# Advantage
# capture information about the structure of words and phrases in a text data set.
# N-grams can provide features that are insensitive to the ordering of words in a sentence.
# N-grams can be used to create features that are more robust to spelling errors and other types of noise in the data
# Finally, n-grams can help to reduce the dimensionality of the feature space

In [96]:
# TD-IDF
# Advantages:
# - Easy to compute
# - You have some basic metric to extract the most descriptive terms in a document
# - You can easily compute the similarity between 2 documents using it

# Disadvantages:
# - TF-IDF is based on the bag-of-words (BoW) model, therefore it does not capture position in text, semantics, co-occurrences in different documents, etc.
# - For this reason, TF-IDF is only useful as a lexical level feature
# - Cannot capture semantics (e.g. as compared to topic models, word embeddings)